traderjoe-xyz/joe-tokenlists

joe.tokenlist.json

Update minor version and add egg and feed token

Chikn Farm Egg and Feed Token

---

README.md

Fix tokenlist tab names typo errors in readme.

Edit tokenlist tags in README.md

---

src/joe.tokenlist-v2.json

Quick one to fix the decimals for fuji USDC and USDT

Fix fuji USDC and USDT decimals

---

src/joe.tokenlist-v2.json

Updating fuji token addresses based on the new set of tokens deployed

Update FUJI tokens addresses

---

src/joe.tokenlist-v2.json

fix tether

---

mc.tokenlist.json

Please merge #700 before.
Thank you in advance,
Romuald.

Add BETS on tokenlist

---

mc.tokenlist.json

Reverts traderjoe-xyz/joe-tokenlists#727

Revert "bnbchain"

---

mc.tokenlist.json

The Fief logo is in this PR https://github.com/traderjoe-xyz/joe-tokenlists/pull/809

Add Fief token info

---

mc.tokenlist.json

ladder (Arb) , logo PR merged 
BTC.B (Bnb) , contract address same with arb hence no PR for logo

ladder and btc.b tokenlist

---

mc.tokenlist.json

Adjusted ACTA to Acta Finance

---

mc.tokenlist.json

Adding SHRAP to token list

---

mc.tokenlist.json

Adding ALEPH to token list

---

mc.tokenlist.json

**This PR: Adds RPG to the verified tokens list.**
**motive**
- Been around for a while, LP locked.
- Currently we are not able to find our token via mobile search.
**website**
https://redponzigud.com/

Add RedPonziGud ($RPG)

---

mc.tokenlist.json

Updating to include SWORD token listing, as approved by BD Unsehrtain in TJ Discord.

Update mc.tokenlist.json - SWORD

---

mc.tokenlist.json

- Contract is verified on Snowtrace.io as required.
- Liquidity has been established, with sufficient number of liquidity providers and consistent 15-day volume as per the guidelines.
- I have tagged the token appropriately in accordance with `mc.tokenlist.json` format.

ATECH Update mc.tokenlist.json

---

mc.tokenlist.json

As we've met the liquidity and volume requirements, we believe we should be added to the list

Added Any Inu to token list

---

mc.tokenlist.json

Reverts traderjoe-xyz/joe-tokenlists#1443

Revert "Update mc.tokenlist.json"

---

mc.tokenlist.json

Add MILLION

---

mc.tokenlist.json

Reverts traderjoe-xyz/joe-tokenlists#1555

Revert "mxs games added to token list"

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0xD036414fa2BCBb802691491E323BFf1348C5F4Ba.

Update tokenlist for MU - 0xD036414fa2BCBb802691491E323BFf1348C5F4Ba

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x77776aB9495729E0939E9bADAf7E7c3312777777.

Update tokenlist for WABBIT - 0x77776aB9495729E0939E9bADAf7E7c3312777777

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x1fCca65fb6Ae3b2758b9b2B394CB227eAE404e1E.

Update tokenlist for pumpBTC - 0x1fCca65fb6Ae3b2758b9b2B394CB227eAE404e1E

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x0256B279D973C8d687264AC3eB36bE09232D4474.

Update tokenlist for MYST - 0x0256B279D973C8d687264AC3eB36bE09232D4474

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x61f23250451305f6C4426E81C50aE535Edf94A02.

Update tokenlist for FTR - 0x61f23250451305f6C4426E81C50aE535Edf94A02

---

mc.tokenlist.json

remove tokens

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x968bE3F7bfeF0F8eDc3c1aD90232EbB0DA0867aA.

Update tokenlist for SWORLD - 0x968bE3F7bfeF0F8eDc3c1aD90232EbB0DA0867aA

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0xA80F36BA18c7f721F3F7ACDbcDEfd3a86869A036.

Update tokenlist for TRUMP - 0xA80F36BA18c7f721F3F7ACDbcDEfd3a86869A036

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x24dE8771bC5DdB3362Db529Fc3358F2df3A0E346.

Update tokenlist for avUSD - 0x24dE8771bC5DdB3362Db529Fc3358F2df3A0E346

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x1c7c53aa86B49A28C627B6450091998e447A42f9.

Update tokenlist for VELAI - 0x1c7c53aa86B49A28C627B6450091998e447A42f9

---

mc.tokenlist.json

This pull request updates the tokenlist to include the token with address 0x73831E7c5577859FB0583aF97C9C68F96A43fcB6.

Update tokenlist for $AIGG - 0x73831E7c5577859FB0583aF97C9C68F96A43fcB6
